<?php

return [
    'admin/product/create' => 'adminProduct/create',
    'admin/product/update/([0-9]+)' => 'adminProduct/update/$1',
    'admin/product/remove/([0-9]+)' => 'adminProduct/remove/$1',
    'admin/product' => 'adminProduct/index',
    'admin/category/create' => 'adminCategory/create',
    'admin/category/update/([0-9]+)' => 'adminCategory/update/$1',
    'admin/category/remove/([0-9]+)' => 'adminCategory/remove/$1',
    'admin/category' => 'adminCategory/index',
    'admin/order/update/([0-9]+)' => 'adminOrder/update/$1',
    'admin/order/remove/([0-9]+)' => 'adminOrder/remove/$1',
    'admin/order/view/([0-9]+)' => 'adminOrder/view/$1',
    'admin/order' => 'adminOrder/index',
    'admin' => 'admin/index',
    'product/([0-9]+)' => 'product/view/$1',
    'catalog/([0-9]+)/cart/add/([0-9]+)' => 'cart/add/$2',
    'catalog/cart/add/([0-9]+)' => 'cart/add/$1',
    'catalog/([0-9])+/page-([0-9]+)' => 'catalog/category/$1/$2',
    'catalog/([0-9])+' => 'catalog/category/$1',
    'catalog' => 'catalog/index',
    'user/login' => 'user/login',
    'user/logout' => 'user/logout',
    'user/register' => 'user/register',    
    'cabinet/edit' => 'cabinet/edit',
    'cabinet/history' => 'cabinet/history',    
    'cabinet' => 'cabinet/index',
    'cart/changecount/([0-9]+)/([0-9]+)' => 'cart/changecount/$1/$2',
    'cart/add/([0-9]+)' => 'cart/add/$1',
    'cart/remove/([0-9]+)' => 'cart/remove/$1',
    'cart/checkout' => 'cart/checkout',
    'cart' => 'cart/view',
    '' => 'site/index'
];